spring.application.name=claims

server.port=8083

spring.datasource.url=jdbc:h2:mem:claimsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=claims_user
spring.datasource.password=claims_password

spring.h2.console.enabled=true

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#
#spring.datasource.url=jdbc:postgresql://dpg-cp12345gcp1234abcd.render.com:5432/test_database_a27k
#spring.datasource.driverClassName=org.postgresql.Driver
#spring.datasource.username=root
#spring.datasource.password=WCle5zihU3dGdo33GQOTvANPzTE4CzuA
#
#spring.h2.console.enabled=true
#
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true