spring.application.name=claims
server.port=8083

# =========================
# H2 Database
# =========================
spring.datasource.h2.jdbc-url=jdbc:h2:mem:claimsdb
spring.datasource.h2.driver-class-name=org.h2.Driver
spring.datasource.h2.username=claims_user
spring.datasource.h2.password=claims_password
spring.h2.console.enabled=true
spring.jpa.h2.hibernate.ddl-auto=update
spring.jpa.h2.show-sql=true
spring.jpa.h2.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# =========================
# Azure SQL Server
# =========================
spring.datasource.sqlserver.jdbc-url=jdbc:sqlserver://forms.database.windows.net:1433;database=FormsAgentCoPilot
spring.datasource.sqlserver.username=admini
spring.datasource.sqlserver.password=Ok@8879463403
spring.datasource.sqlserver.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.sqlserver.hibernate.ddl-auto=update
spring.jpa.sqlserver.show-sql=true
spring.jpa.sqlserver.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# =========================
# PostgreSQL Configuration
# =========================
#spring.datasource.pg.jdbc-url=jdbc:postgresql://dpg-d4hv31umcj7s73c9hl80-a.oregon-postgres.render.com:5432/test_database_a27k?sslmode=require
#spring.datasource.pg.username=root
#spring.datasource.pg.password=WCle5zihU3dGdo33GQOTvANPzTE4CzuA
#spring.datasource.pg.driver-class-name=org.postgresql.Driver
#
#spring.jpa.pg.hibernate.ddl-auto=create
#spring.jpa.pg.show-sql=true
#spring.jpa.pg.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect