spring.application.name=claims
server.port=8083

########################################################
# PRIMARY DATABASE ? H2
########################################################
spring.datasource.h2.jdbc-url=jdbc:h2:mem:claimsdb
spring.datasource.h2.driver-class-name=org.h2.Driver
spring.datasource.h2.username=claims_user
spring.datasource.h2.password=claims_password

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# H2 JPA properties (H2 gets default JPA config)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


##############################
# AZURE SQL SERVER (DB2)
##############################

spring.datasource.sqlserver.jdbc-url=jdbc:sqlserver://forms.database.windows.net:1433;database=FormsAgentCoPilot;
spring.datasource.sqlserver.username=admini@forms
spring.datasource.sqlserver.password=Ok@8879463403
spring.datasource.sqlserver.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate
spring.jpa.sqlserver.hibernate.ddl-auto=update
spring.jpa.sqlserver.show-sql=true
spring.jpa.sqlserver.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect


########################################################
# SECONDARY DATABASE ? POSTGRES
########################################################
#spring.datasource.pg.jdbc-url=jdbc:postgresql://dpg-d4hv31umcj7s73c9hl80-a.oregon-postgres.render.com:5432/test_database_a27k?sslmode=require
#spring.datasource.pg.username=root
#spring.datasource.pg.password=WCle5zihU3dGdo33GQOTvANPzTE4CzuA
#spring.datasource.pg.driver-class-name=org.postgresql.Driver
#
#spring.jpa.pg.hibernate.ddl-auto=update
#spring.jpa.pg.show-sql=true
#spring.jpa.pg.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect





#postgresql://root:WCle5zihU3dGdo33GQOTvANPzTE4CzuA@dpg-d4hv31umcj7s73c9hl80-a.oregon-postgres.render.com/test_database_a27k
#
#spring.datasource.url=jdbc:postgresql://dpg-cp12345gcp1234abcd.render.com:5432/test_database_a27k
#spring.datasource.driverClassName=org.postgresql.Driver
#spring.datasource.username=root
#spring.datasource.password=WCle5zihU3dGdo33GQOTvANPzTE4CzuA
#
#spring.h2.console.enabled=true
#
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true